import type { QuizLocale } from './types';

const hi: QuizLocale = {
  ui: {
    eyebrow: 'आइडेंटिटी असेसमेंट',
    heroLine1: 'आप दुनिया को',
    heroLine2: 'कैसे देखते हैं?',
    subtitle: 'पाँच सवाल। आठ विकल्प। कोई सही जवाब नहीं — सिर्फ़ खुलासा करने वाले।',
    startButton: 'क्विज़ शुरू करें',
    previous: 'पिछला',
    next: 'अगला',
    seeResults: 'परिणाम देखें',
    questionOf: (c, t) => `सवाल ${c} / ${t}`,
    answeredOf: (a, t) => `${t} में से ${a} के जवाब दिए`,
    yourResult: 'आपका परिणाम',
    breakdownEyebrow: 'सवाल-दर-सवाल विश्लेषण',
    breakdownHeading: 'हर जवाब क्या बताता है',
    question: (n) => `सवाल ${n}`,
    yourAnswer: 'आपका जवाब',
    feedback: 'फ़ीडबैक',
    retake: 'दोबारा करें',
    exploreFellowship: 'फ़ेलोशिप के बारे में जानें',
    backToHome: 'होम पर वापस जाएँ',
    scoreLabels: {
      exceptional: 'असाधारण',
      strong: 'मज़बूत',
      developing: 'विकासशील',
      emerging: 'प्रारंभिक',
    },
    insights: {
      exceptional: 'आप दुनिया को एक ऐसे नज़रिए से देखते हैं जो ज़्यादातर लोग कभी विकसित नहीं कर पाते। आपकी सहज प्रवृत्तियाँ उस सोच के अनुरूप हैं जो यह काम माँगता है।',
      strong: 'मज़बूत नींव जिसमें और धार लाने की गुंजाइश है। आपके पास कच्चा माल है — फ़ेलोशिप इसे निखारने के लिए ज़रूरी अनुभव देगी।',
      developing: 'आप निर्माण कर रहे हैं। कुछ प्रवृत्तियाँ हैं, कुछ को जानबूझकर विकसित करने की ज़रूरत है। फ़ेलोशिप ठीक इसी के लिए बनाई गई है।',
      emerging: 'आप इस यात्रा की शुरुआत में हैं। यह कमज़ोरी नहीं है — यह शुरुआती बिंदु है। सबसे अच्छे फ़ेलो अक्सर यहीं से शुरू करते हैं और सबसे तेज़ बढ़ते हैं।',
    },
  },
  data: {
    maxScorePerQuestion: 8,
    questions: [
      {
        id: 1,
        text: 'आप एक social gathering में हैं। कोई बिल्कुल अलग industry का व्यक्ति पूछता है, "आप क्या करते हैं? काम कैसा चल रहा है?"',
        options: [
          { id: '1a', text: 'मैं अपनी company का नाम और role बता देता हूँ। बात वहीं खत्म हो जाती है क्योंकि मैं समझा नहीं पाता कि मैं actually करता क्या हूँ, और मैं उनके काम के बारे में कुछ पूछता भी नहीं।' },
          { id: '1b', text: 'मैं बताता हूँ कि मैं consulting और tech में हूँ और बहुत कुछ सीख रहा हूँ। हम दोनों अपनी-अपनी job descriptions share करते हैं और आगे बढ़ जाते हैं। अगर कोई पूछे कि मेरी skills मेरे level के बाकी लोगों से अलग कैसे हैं, तो मेरे पास जवाब नहीं होगा।' },
          { id: '1c', text: 'मैं बताता हूँ कि इस काम में मुझे क्या खींचा और मैं क्या सीख रहा हूँ। मुझे उनके field में genuine curiosity है, लेकिन बातचीत polite और अलग-अलग रहती है। मेरे दिमाग में यह नहीं आता कि उनकी problems मेरी problems जैसी हो सकती हैं।' },
          { id: '1d', text: 'मेरे पास एक कहानी है जो मेरे career moves को जोड़ती है और relaxed settings में अच्छी लगती है। लेकिन अगर कोई recruiter ज़ोर से पूछे या घर पर parents यही सवाल करें, तो मैं कहानी छोड़ कर job title और salary पर आ जाऊँगा। बातचीत friendly है लेकिन हम दोनों अपनी-अपनी दुनिया में रहते हैं।' },
          { id: '1e', text: 'मैं बता सकता हूँ कि मैंने यह path क्यों चुना, कौन सी specific skill बना रहा हूँ, और वो skill क्यों ज़्यादा valuable हो रही है। मैं उनसे पूछता हूँ कि उनकी problems क्या हैं, title नहीं, क्योंकि मैंने notice किया है कि अलग-अलग industries में same problems आती हैं और मैं check करना चाहता हूँ कि उनकी problem मेरे किसी काम से जुड़ती है या नहीं।' },
          { id: '1f', text: 'मैं बात करता हूँ कि मेरा career किस direction में जा रहा है, यह नहीं कि मैंने क्या-क्या किया है। मुझे पता है कि मैं किसमें अच्छा हूँ और वो combination hire करना क्यों मुश्किल है। मैं बातचीत को उनके field की तरफ ले जाता हूँ क्योंकि मैं कुछ ऐसा सुनना चाहता हूँ जो मेरी current सोच को contradict करे।' },
          { id: '1g', text: 'मैं बात करता हूँ कि कहाँ जा रहा हूँ, कहाँ से आया हूँ नहीं। मैं अपने career bet का math दिखा सकता हूँ: क्या छोड़ा, क्या बनाया, अब उसकी value क्या है। मैं अपने काम की specific problems बातचीत में लाता हूँ क्योंकि मुझे पहले भी अलग industries के लोगों से usable ideas मिले हैं।' },
          { id: '1h', text: 'मैं अपना role describe नहीं करता। मैं वो specific problem describe करता हूँ जो मैं solve करता हूँ, और वो problem ज़्यादातर लोग तुरंत पहचान लेते हैं। मैं उनसे पूछता हूँ कि उनकी industry में क्या टूटा हुआ है, क्योंकि इसके जवाब ने मेरा काम एक से ज़्यादा बार बदला है।' },
        ],
      },
      {
        id: 2,
        text: 'आपने एक काम पूरा किया। आपके manager ने review किया और बोला, "अच्छा है, client को भेज दो।" कुछ आपको खटक रहा है।',
        options: [
          { id: '2a', text: 'Manager ने बोला अच्छा है। मैं भेज देता हूँ। Task complete है और ऊपर वाले ने approve कर दिया, तो मेरे लिए process खत्म है।' },
          { id: '2b', text: 'मैं पिछली बार के similar deliverable से compare करता हूँ। Same format, same structure। Match करता है, तो भेज देता हूँ। कुछ खटकता है लेकिन समझ नहीं आ रहा क्या, और template check तो pass हो गया।' },
          { id: '2c', text: 'मुझे लगता है कुछ गड़बड़ है लेकिन exactly बता नहीं पा रहा। Manager ने approve किया है तो भेज देता हूँ। बाद में, client की reaction देखकर, समझ आता है कि क्या गलत था। Gap sense कर पा रहा था लेकिन time पर diagnose नहीं कर पाया।' },
          { id: '2d', text: 'काम पूरा होने के बाद, मैं बता सकता हूँ कि कहाँ कमज़ोर है। Analysis सही है लेकिन framing इस audience के लिए land नहीं करेगी। Manager को बताता हूँ लेकिन ज़्यादा push नहीं करता। अगर वो बोलें भेज दो, तो भेज देता हूँ।' },
          { id: '2e', text: 'मुझे पता है कि इस type के काम में good कैसा दिखता है। मैं exactly बता सकता हूँ कि यह कहाँ कम पड़ रहा है और क्यों। एक section confusion बढ़ा रहा है बिना value add किए। मैं manager को बोलता हूँ: यह हिस्सा काटना या rewrite करना चाहिए भेजने से पहले।' },
          { id: '2f', text: 'कमज़ोर section बनाते हुए ही पकड़ लिया था और किसी को दिखाने से पहले fix करने की कोशिश की। जब manager बोलता है भेज दो, मैं specific हिस्से की तरफ point करता हूँ: "यह section बहुत ज़्यादा cover करने की कोशिश कर रहा है। इसे आधा करूँ? छोटा होगा लेकिन actually land करेगा।"' },
          { id: '2g', text: 'मुझे कुछ ऐसा दिखता है जो किसी और ने flag नहीं किया। Formatting problem नहीं। Recommendation client की actual situation से टकराकर नहीं टिकेगी क्योंकि हम उनके operations के बारे में कुछ assume कर रहे हैं जो verify नहीं किया। Manager को लगता है ready है, फिर भी मैं raise करता हूँ।' },
          { id: '2h', text: 'किसी को दिखाने से पहले ही सबसे कमज़ोर हिस्सा ढूँढ लिया था। यह भी पता है कब रुकना है। एक section rework चाहिए और मैं exactly बता सकता हूँ क्यों। बाकी सही है और ज़्यादा polish करने से improve नहीं होगा। कमज़ोर हिस्सा fix करता हूँ, बाकी छोड़ देता हूँ, और भेज देता हूँ।' },
        ],
      },
      {
        id: 3,
        text: 'आपके साथ graduate हुआ दोस्त एक बड़ी company में जाकर 40% raise ले आया। Coffee पर बोलता है: "तू तो smart है, तू भी कर सकता है। क्यों रुका है वहाँ?"',
        options: [
          { id: '3a', text: 'शायद वो सही कह रहा है। मुझे ज़्यादा मिलेगा। मेरी जगह छोटी है, कम पैसे हैं, और कोई नाम नहीं पहचानता। शायद apply करना शुरू करना चाहिए।' },
          { id: '3b', text: 'मुझे पता है कि मैं यहाँ ज़्यादा कर रहा हूँ। लेकिन exactly बता नहीं पाता कि यह क्यों matter करता है। जब वो salary पर push करता है, तो मेरे पास अच्छा जवाब नहीं होता।' },
          { id: '3c', text: 'मुझे दिखने लगा है कि मुझे यहाँ ऐसी चीज़ें करने मिलती हैं जो दोस्त को उसकी company में कभी छूने नहीं मिलेंगी। मेरी profile unusual बन रही है। लेकिन अभी पूरा explain नहीं कर पाता, और salary का फ़र्क अभी भी खटकता है।' },
          { id: '3d', text: 'अच्छे हफ्ते के बाद, मुझे exactly पता है क्यों यहाँ हूँ। Freedom, experiments, unusual profile। बुरे हफ्ते के बाद, दोस्त की salary देखता हूँ और सोचता हूँ शायद वो सही कह रहा है। Options open रखता हूँ बस case में।' },
          { id: '3e', text: 'मुझे पता है क्यों यहाँ हूँ और explain कर सकता हूँ। मुझे diagnose, design, और outcomes end to end own करने मिलता है। बड़ी company में मेरे level पर किसी को यह नहीं मिलता। मेरी profile ऐसे intersection पर बैठती है जहाँ कोई और नहीं है। Salary gap आज real है, लेकिन जो बना रहा हूँ वो gap close करेगा और फिर पार कर जाएगा।' },
          { id: '3f', text: 'मैंने सोचना बंद कर दिया है कि रुकूँ या जाऊँ। मैं इस environment का इस्तेमाल अपने design किए experiments चलाने के लिए कर रहा हूँ। हर मुश्किल project कुछ सिखाता है जो कहीं और नहीं मिलता। मैंने जानबूझकर अपनी profile के वो हिस्से छोड़ दिए जो सबके जैसे दिखते थे और जो unique है उस पर double down किया।' },
          { id: '3g', text: 'मेरा हर project पिछले से सीखी चीज़ पर बनता है। मैं एक ऐसा approach develop कर रहा हूँ जो मेरे शुरू करने से पहले exist नहीं करता था। मैं chain trace कर सकता हूँ: project 1 ने X सिखाया, जिसने project 2 possible बनाया, जिसने Y produce किया। दोस्त की raises linear हैं। मेरा career compound हो रहा है। मैंने यह niche दूसरों को explain करना शुरू किया है क्योंकि इसका कोई नाम नहीं है अभी।' },
          { id: '3h', text: 'मैंने कुछ ऐसा बनाया है जो मेरे शुरू करने से पहले exist नहीं करता था। Experiments, methodology, category। यह सब मेरे आने से पहले यहाँ नहीं था। दोस्त salaries compare कर रहा है। मैं उसी axis पर हूँ ही नहीं अब। अगर कोई double offer करे, तो calculate करूँगा कि momentum में क्या cost आएगा, और जवाब बहुत convincing होना चाहिए।' },
        ],
      },
      {
        id: 4,
        text: 'आप client के CEO के साथ meeting में हैं। वो एक ऐसी business problem describe करने लगते हैं जिसका आपके assigned काम से कोई लेना-देना नहीं।',
        options: [
          { id: '4a', text: 'Note कर लेता हूँ लेकिन मेरा काम नहीं है। मैं specific task के लिए यहाँ हूँ। CEO की problem business issue है और मैं tech person हूँ। बातचीत मेरे scope पर वापस आने का इंतज़ार करता हूँ।' },
          { id: '4b', text: 'सुनता हूँ क्योंकि CEO को business के बारे में बात करते सुनना interesting है। Meeting के बाद अपने assigned काम पर वापस आ जाता हूँ। शायद manager को गुज़रते हुए बता दूँ।' },
          { id: '4c', text: 'Realize होता है कि यह business problem शायद मेरे technical काम से connect है। शायद इस problem का data मेरे बना रहे system में दिखना चाहिए। Note कर लेता हूँ और बाद में सोचता हूँ।' },
          { id: '4d', text: 'CEO से एक follow-up question पूछता हूँ। Desk पर वापस आकर सोचता हूँ कि क्या इसे अपने काम में factor करना चाहिए। लेकिन sure नहीं कि assigned scope के बाहर time देना expected है या overstepping।' },
          { id: '4e', text: 'CEO से request करता हूँ कि problem detail में बताएँ। "Actually step by step क्या होता है?" Realize होता है कि मेरा technical काम इस business workflow से शुरू होना चाहिए, उस data से नहीं जो मुझे दिया गया। Business context मेरा design बदल देता है।' },
          { id: '4f', text: 'ऐसे questions पूछता हूँ जो CEO मेरी role से expect नहीं करता। "Order release करने से पहले आपकी team क्या check करती है? कहाँ किसी और का इंतज़ार करती है?" Realize होता है कि CEO की problem और मेरा assigned काम same problem है अलग-अलग angle से। दोनों में change propose करता हूँ।' },
          { id: '4g', text: 'Request करता हूँ कि जिस team को problem है उनके साथ time बिताऊँ। देखता हूँ कि वो actually क्या करते हैं, CEO क्या सोचता है नहीं। असली bottleneck CEO ने जो describe किया उससे अलग निकलता है। मेरा solution tech, business understanding, और process knowledge तीनों मिलाकर बनता है। सिर्फ एक में specialist यह नहीं ढूँढ पाता।' },
          { id: '4h', text: 'महीनों से हर client meeting में यही कर रहा हूँ। जब भी CEO business problem mention करता है, मैं उसे अपने काम की starting point बनाता हूँ। जो solutions बनाता हूँ वो सिर्फ technical issue fix नहीं करते। Teams कैसे साथ काम करती हैं वो बदलते हैं। CEO ने यह नहीं माँगा था। लेकिन जब देखता है तो पहचानता है।' },
        ],
      },
      {
        id: 5,
        text: 'Client की एक problem हर quarter वापस आ रही है। आपसे फिर fix करने को बोला गया है।',
        options: [
          { id: '5a', text: 'पिछली बार जैसे fix किया वैसे ही करता हूँ। हर बार वापस आती है तो नया task मानता हूँ। क्यों बार-बार हो रही है यह नहीं पूछता।' },
          { id: '5b', text: 'Fix करता हूँ, लेकिन notice करता हूँ कि यह तीसरी बार है। Manager को mention करता हूँ कि बार-बार हो रही है। क्यों हो रही है इसमें नहीं जाता क्योंकि fix पूरा करने पर focus है।' },
          { id: '5c', text: 'Pattern notice करता हूँ। यह problem हर quarter similar conditions में वापस आती है। सोचता हूँ कि कुछ structural reason है। लेकिन symptom फिर fix कर देता हूँ क्योंकि यही करने को बोला गया है।' },
          { id: '5d', text: 'Map करता हूँ कि problem से क्या-क्या connected है। One-off नहीं है। दो teams के बीच handoff कैसे होता है उससे जुड़ा है। Structural fix propose करता हूँ। लेकिन जब manager बोलता है "बस पहले वाले तरीके से fix कर दो," तो push नहीं करता।' },
          { id: '5e', text: 'Recurring problem को trace करता हूँ उस feedback loop तक जो cause कर रहा है। असली issue quarterly symptom नहीं है। System के दो हिस्सों के बीच information कैसे flow होती है, वो है। Root cause present करता हूँ और structure fix करने propose करता हूँ, symptom नहीं। यह भी recognize करता हूँ कि इस type का diagnosis वो specific skill है जो हर ऐसी interaction से better हो रही है।' },
          { id: '5f', text: 'Leverage point ढूँढता हूँ: system में वो एक जगह जहाँ छोटा change problem को वापस आने से रोकता है। यह भी देखता हूँ कि problem इसलिए exist करती है क्योंकि दो groups जिन्हें बात करनी चाहिए, नहीं कर रहे। खुद को उस gap पर position करता हूँ।' },
          { id: '5g', text: 'देखता हूँ कि recurring problem सिर्फ इस client का issue नहीं है। यह reflect करती है कि इस growth stage की businesses कैसे काम करती हैं। Multiple clients में same pattern देख चुका हूँ। इस class की problem diagnose और fix करने का approach बना रहा हूँ। यह भी देखता हूँ कि इसे fix करने की ability ज़्यादा valuable हो रही है क्योंकि ज़्यादा companies इस stage पर पहुँच रही हैं।' },
          { id: '5h', text: 'Recurring problem सिर्फ fix नहीं करता। Client इस type की problem के बारे में कैसे सोचता है, वो बदलता हूँ। उन्हें वो mental model दिखाता हूँ जो बार-बार produce कर रहा है। हर बार अलग client में यह करता हूँ, pattern तेज़ी से recognize करने लगता हूँ। एक ऐसी class की problem के around practice बना रहा हूँ जो ज़्यादातर लोग one-offs मानते हैं।' },
        ],
      },
    ],
    rubric: [
      {
        questionId: 1,
        scoring: { '1a': 1, '1b': 2, '1c': 3, '1d': 4, '1e': 5, '1f': 6, '1g': 7, '1h': 8 },
        feedback: {
          '1a': 'आप title बताते हैं और आगे बढ़ जाते हैं। Professional बातचीत अभी opportunity की तरह नहीं दिखती। ज़्यादातर लोग यहीं से शुरू करते हैं। अगला कदम: ध्यान दीजिए कि सामने वाला भी problems solve करता है। उनकी problems आपको अपने काम के बारे में कुछ सिखा सकती हैं।',
          '1b': 'आप descriptions share करते हैं और familiar चीज़ों में common ground ढूँढते हैं। आप जानते हैं कि आपके काम में label से ज़्यादा कुछ है, लेकिन शब्द नहीं मिल रहे अभी। अगला कदम: role describe करने की बजाय, बताइए कि इस काम में क्या खींचा और क्या सीख रहे हैं।',
          '1c': 'आप genuine curiosity लाते हैं और अपना काम clearly समझा सकते हैं। बातचीत अच्छी होती है लेकिन safe territory में रहती है। अगला कदम: सामने वाले से उनके role की बजाय, उनकी problems पूछिए। अलग-अलग industries में अक्सर same problems होती हैं, बस भेस बदला हुआ होता है।',
          '1d': 'आपके पास अपने career की एक असली कहानी है जो relaxed settings में अच्छी लगती है। जब दाँव बढ़ता है, कहानी गिर जाती है और title ले लेता है। अगला कदम: कहानी को मुश्किल rooms में test कीजिए। जब recruiter push करे या family सवाल करे, narrative पकड़े रहिए। अगर टूटती है, तो weak point दिखा देगी कि कहाँ मज़बूत करना है।',
          '1e': 'आप जानते हैं कि क्या बना रहे हैं, क्यों valuable है, और actively industries में connections ढूँढते हैं। आपकी कहानी stable और specific है। अगला कदम: ऐसे लोगों को ढूँढना शुरू कीजिए जो आपसे अलग सोचते हैं, सिर्फ अलग industry वाले नहीं। ऐसे perspectives खोजिए जो आपकी current सोच को challenge करें, सिर्फ expand न करें।',
          '1f': 'आप बातचीत का इस्तेमाल अपनी सोच को challenge करने के लिए करते हैं, सिर्फ दूसरों से सीखने के लिए नहीं। आपको पता है कि आपकी profile क्यों rare है और आप सीधे बोलते हैं। अगला कदम: track करना शुरू कीजिए कि कौन सी बातचीत ने actually आपका काम बदला। अलग-अलग fields में कुछ लोगों का एक छोटा group बनाइए जिनसे आप regularly बात करें, सिर्फ एक बार नहीं।',
          '1g': 'आपके पास proof है। आप अपने career bet का math trace कर सकते हैं और returns दिखा सकते हैं। Industries के बीच बातचीत से ऐसे ideas आते हैं जो अगले हफ्ते काम आते हैं। अगला कदम: जो problem आप solve करते हैं, उसे ऐसे शब्दों में बताइए जो कोई भी listener तुरंत पहचान ले, बिना industry jargon के। जब आप ऐसा करेंगे, बातचीत pattern के बारे में होगी, आपके बारे में नहीं।',
          '1h': 'आप अपना role नहीं, जो problem solve करते हैं वो describe करते हैं, और वो problem ज़्यादातर लोग तुरंत पहचान लेते हैं। अलग-अलग fields के लोगों से बातचीत ने आपका काम एक से ज़्यादा बार बदला है। आप इन dimensions पर highest level पर हैं। आपकी growth अब दूसरों को वही clarity develop करने में help करने से आएगी जो आपके पास है।',
        },
      },
      {
        questionId: 2,
        scoring: { '2a': 1, '2b': 2, '2c': 3, '2d': 4, '2e': 5, '2f': 6, '2g': 7, '2h': 8 },
        feedback: {
          '2a': 'आप completion check करते हैं। ऊपर वाले ने approve किया तो process खत्म। ज़्यादातर लोग यहीं से शुरू करते हैं। अगला कदम: अगले deliverable के बाद, किसी के review करने से पहले, खुद से एक सवाल पूछिए: "क्या यह इस type के काम का best version है जो मैंने देखा है?" बस यह comparison eye बनाना शुरू करती है।',
          '2b': 'आप past examples और templates से compare करते हैं। Match हो गया तो सही लगता है। अगला कदम: templates format capture करते हैं, सोच नहीं। अगली बार जब कुछ खटके, रुकिए और name करने की कोशिश कीजिए कि क्या गलत है। अभी fix नहीं कर पाते तो भी, name करना पहला कदम है।',
          '2c': 'आप sense करते हैं जब कुछ गड़बड़ है लेकिन हमेशा name नहीं कर पाते। Instinct vocabulary से तेज़ develop हो रहा है। अगला कदम: जब वो feeling आए, रुकिए और तीन चीज़ें पूछिए। Audience कौन है? इसे पढ़ने के बाद उन्हें क्या decide करना है? सबसे कमज़ोर section उस decision में help करता है? Audience name करने से diagnosis sharp होती है।',
          '2d': 'आप बता सकते हैं कि कहाँ कमज़ोर है और क्यों। Mention करते हैं लेकिन senior disagree करे तो push नहीं करते। Diagnosis सही है। अगला कदम: practice कीजिए बोलने का "मुझे लगता है यह specific section भेजने से पहले rework चाहिए, इसलिए" और position पकड़े रहिए। Judgment पहले से है। Conviction उसके बराबर आना चाहिए।',
          '2e': 'आपके पास clear picture है कि इस type के काम में good कैसा दिखता है। आप exactly बता सकते हैं कि कहाँ कम है और क्यों। अगला कदम: gap बनते हुए पकड़ना शुरू कीजिए, बाद में नहीं। अगर काम करते-करते लगे कि standard से drift हो रहा है, तो finish करने से पहले direction बदलिए। यह फ़र्क है काम के बाद सोचने और काम करते हुए सोचने में।',
          '2f': 'आप problems बनाते हुए पकड़ते हैं और किसी को दिखाने से पहले fix करते हैं। Challenge होने पर specific section point करके बताते हैं कि क्या गलत है। अगला कदम: वो चीज़ ढूँढिए जो room में किसी और ने flag नहीं की। Formatting या clarity नहीं, बल्कि यह कि recommendation client की असली situation से टकराकर टिकेगी या नहीं। इसके लिए business context और technical quality दोनों एक ही frame में hold करने होते हैं।',
          '2g': 'आप वो देखते हैं जो बाकी miss कर देते हैं। Surface problems नहीं बल्कि structural: assumptions जो verify नहीं हुई, conditions जो data gather करने के बाद बदल गई। अगला कदम: रुकना भी जानिए। किसी को दिखाने से पहले सबसे कमज़ोर हिस्सा ढूँढिए, लेकिन यह भी जानिए कि बाकी कब ship करने लायक है। सबसे मुश्किल judgment problems ढूँढना नहीं है। यह जानना है कि और refine करना काम serve कर रहा है या आपकी अपनी बेचैनी।',
          '2h': 'आप किसी को दिखाने से पहले सबसे कमज़ोर हिस्सा ढूँढते हैं, और पता है कि बाकी कब done है। Diminishing returns से आगे polish नहीं करते। हर deliverable "good" की आपकी definition sharpen करता है। आप इन dimensions पर highest level पर हैं। आपकी growth अब दूसरों में वही quality eye develop करने से आएगी जो आपके पास है।',
        },
      },
      {
        questionId: 3,
        scoring: { '3a': 1, '3b': 2, '3c': 3, '3d': 4, '3e': 5, '3f': 6, '3g': 7, '3h': 8 },
        feedback: {
          '3a': 'आपको salary gap दिख रहा है और लग रहा है पीछे रह रहे हैं। जो agency और experimentation available है वो अभी valuable नहीं दिख रही। ज़्यादातर लोग यहीं से शुरू करते हैं। अगला कदम: compare कीजिए कि आप हफ्ते में क्या करते हैं और दोस्त क्या करता है। Pay नहीं। Tasks। Freedom। कौन सी problems छूने मिलती हैं। वो comparison अलग कहानी बताता है।',
          '3b': 'आप जानते हैं कि ज़्यादा कर रहे हैं, लेकिन salary पर push आने पर शब्द नहीं मिलते। अगला कदम: एक specific चीज़ बताइए जो पिछले महीने की जो आपके दोस्त की role में कभी करने नहीं मिलती। Name कीजिए। ज़ोर से बोलकर practice कीजिए। Argument एक concrete example से शुरू होता है, general feeling से नहीं।',
          '3c': 'आपको लग रहा है कि profile unusual बन रही है। Experiments, freedom, range। लेकिन "यह कहाँ जा रहा है?" का clear जवाब अभी नहीं है। अगला कदम: unusual profile को specific outcome से जोड़िए। "मैं वो skill बना रहा हूँ जिससे ___" यह sentence पूरा कीजिए। Path तब दिखती है।',
          '3d': 'अच्छे हफ्ते के बाद conviction असली है। बुरे हफ्ते के बाद salary comparison जीत जाती है। अगला कदम: अच्छे हफ्ते में लिख लीजिए कि क्यों यहाँ हैं। बुरे हफ्ते में पढ़िए। अगर reasoning नहीं टिकती, तो problem reasoning में है, हफ्ते में नहीं। अगर टिकती है, तो problem यह है कि conviction अभी durable नहीं है। Durability evidence से आती है, enthusiasm से नहीं।',
          '3e': 'आपको पता है क्यों यहाँ हैं, explain कर सकते हैं, और explanation pressure में भी टिकती है। Profile ऐसे intersection पर है जहाँ ज़्यादातर लोग पहुँच नहीं सकते। अगला कदम: explain करना बंद कीजिए कि क्यों रुके हैं और ऐसे experiments शुरू कीजिए जो किसी ने माँगे नहीं। Agency आपकी है। इसका इस्तेमाल कुछ ऐसा बनाने में कीजिए जो सिर्फ यह environment possible बनाता है।',
          '3f': 'आपने रुकने-जाने की बहस बंद कर दी। Environment को lab की तरह इस्तेमाल कर रहे हैं, अपने experiments चला रहे हैं, और जानबूझकर वो बना रहे हैं जो profile unique करे। अगला कदम: experiments को एक-दूसरे से जोड़िए। हर experiment पिछले वाले से सीखी चीज़ पर बने। Compounding तब शुरू होती है जब experiments एक chain बनें, list नहीं।',
          '3g': 'आप chain trace कर सकते हैं: project 1 ने X सिखाया, जिसने project 2 possible बनाया, जिसने Y produce किया। Career compound हो रहा है और math दिखा सकते हैं। अगला कदम: अगर कल कोई double salary offer करे, तो calculate कर सकते हैं कि momentum में क्या cost आएगा? वो calculation strong position और unbreakable position के बीच का फ़र्क है।',
          '3h': 'आपने कुछ ऐसा बनाया जो शुरू करने से पहले exist नहीं करता था। Experiments, methodology, category। Salary comparison लागू नहीं होती क्योंकि आप उसी axis पर हैं ही नहीं। आप इन dimensions पर highest level पर हैं। आपकी growth अब दूसरों को वही compounding logic अपने काम में दिखाने में help करने से आएगी।',
        },
      },
      {
        questionId: 4,
        scoring: { '4a': 1, '4b': 2, '4c': 3, '4d': 4, '4e': 5, '4f': 6, '4g': 7, '4h': 8 },
        feedback: {
          '4a': 'आप अपना scope clearly देखते हैं और उसके अंदर रहते हैं। CEO की business problem आपके काम से जुड़ी हुई register नहीं हुई। ज़्यादातर लोग यहीं से शुरू करते हैं। अगला कदम: अगली बार जब कोई आपके scope के बाहर की problem describe करे, एक सवाल पूछिए। बस एक। देखिए जवाब आपके काम से connect होता है या नहीं।',
          '4b': 'आप सुनते हैं और interesting लगता है लेकिन अपने काम से connect नहीं करते। अगला कदम: अगली meeting के बाद जहाँ कोई scope के बाहर की problem mention करे, एक sentence लिखिए: "यह problem मेरे काम से connect हो सकती है क्योंकि ___।" Guess भी करें तो भी, यह muscle बनना शुरू होती है जो proximity को insight में बदलती है।',
          '4c': 'आप देख सकते हैं कि business problem technical काम से connect हो सकती है। Connection बन रहा है। अगला कदम: thread pull कीजिए। पूछिए "actually step by step क्या होता है?" Detail में ही business problem और technical solution का असली connection दिखता है। आपने जो note लिखा वो शुरुआत है। Follow-up question उसे useful बनाता है।',
          '4d': 'आप follow-up question पूछते हैं और connection sense करते हैं। लेकिन sure नहीं कि assigned scope के बाहर जाना expected है या overstepping। अगला कदम: overstepping नहीं है। Business context design में आने से आपका काम बेहतर होता है। अगली बार, सोचने की बजाय propose कीजिए: "मुझे लगता है यह मेरे काम से connect है। ऐसे।" Worst case कोई बोलेगा "focus रखो।" Best case आपका काम बड़ी problem solve करेगा।',
          '4e': 'आप CEO से problem detail में walk through कराते हैं। Business context technical design बदल देता है क्योंकि आप workflow से शुरू कर रहे हैं, spec से नहीं। अगला कदम: ऐसे questions पूछना शुरू कीजिए जो CEO आपकी role से expect नहीं करता। वहाँ देखिए जहाँ दो teams या processes को बात करनी चाहिए लेकिन नहीं कर रहे। वो gap ही वो जगह है जहाँ usually असली problem रहती है।',
          '4f': 'आप अपनी expected role से बाहर questions पूछते हैं और पाते हैं कि CEO की problem और assigned काम same problem है अलग angles से। अगला कदम: जाकर उस team के साथ बैठिए जिसे problem है। लोग जो काम करते हैं वो CEO ने जो describe किया उससे अलग होगा। असली bottleneck usually उस gap में होता है जो leadership देखती है और ground floor actually करता है।',
          '4g': 'आप team के साथ बैठते हैं, actually क्या करते हैं वो देखते हैं, और describe किए गए से अलग bottleneck ढूँढते हैं। Solution tech, business understanding, और process knowledge तीनों से बनता है। अगला कदम: आप एक client में यह कर रहे हैं। Clients के across pattern notice करना शुरू कीजिए। Same class की problem हर growing company में आती है, बस अलग-अलग भेस में। Pattern पहचानना one-time fix को repeatable skill में बदलता है।',
          '4h': 'हर client meeting business problem से शुरू होती है, technical scope से नहीं। आपके solutions teams कैसे साथ काम करती हैं वो बदलते हैं क्योंकि आपने पूरा system देखने की आदत बना ली है। आप इन dimensions पर highest level पर हैं। आपकी growth अब इतने consistently करने से आएगी कि दूसरे आपको देखकर approach सीखें।',
        },
      },
      {
        questionId: 5,
        scoring: { '5a': 1, '5b': 2, '5c': 3, '5d': 4, '5e': 5, '5f': 6, '5g': 7, '5h': 8 },
        feedback: {
          '5a': 'आप जो सामने है वो fix करते हैं। हर बार problem वापस आती है तो नया task है। ज़्यादातर लोग यहीं से शुरू करते हैं। अगला कदम: अगली बार recurring problem fix करते हुए एक question पूछिए: "क्या यह पिछली बार जैसी ही problem है या अलग?" अगर same है, तो fix काम नहीं कर रहा। यह investigate करने लायक है।',
          '5b': 'आप pattern notice करते हैं और mention करते हैं। क्यों हो रही है इसमें नहीं जाते क्योंकि assignment fix करना है, investigate करना नहीं। अगला कदम: अगली बार "बार-बार हो रहा है" बोलते हुए, 30 मिनट लगाकर देखिए कि recurring instances में common क्या है। Quarter का कौन सा time, कौन सी team, कौन सा workflow step। Pattern उस data में है जो पहले से आपके पास है।',
          '5c': 'आप pattern देखते हैं और सोचते हैं कि कुछ structural है। Symptom fix करते हैं क्योंकि यही माँगा गया। अगला कदम: symptom से एक कदम पीछे trace कीजिए। अगर problem हर बार same जगह से शुरू होती है, कुछ upstream produce कर रहा है। Symptom से एक कदम और आगे जाइए। वो एक कदम अक्सर असली cause दिखा देता है।',
          '5d': 'आपने structure map किया और root cause के लिए fix propose किया। Resistance आने पर push नहीं किया। Structural fix सही था। अगला कदम: cost argument की तरह present कीजिए। "Root cause fix करें तो हर quarter इस problem पर X hours खर्च करना बंद होगा जो exist ही नहीं करनी चाहिए।" ऐसे frame कीजिए कि na बोलना ज़्यादा costly लगे। Reasoning तो है। Persuasion उसके बराबर आना चाहिए।',
          '5e': 'आपने problem को उस feedback loop तक trace किया जो produce कर रहा है। Root cause दिखता है और recognize करते हैं कि यह diagnosis ही वो specific skill है जो बना रहे हैं। अगला कदम: leverage point ढूँढिए। सिर्फ root cause नहीं, वो एक जगह जहाँ छोटा change पूरे loop को चलने से रोकता है। Intervention वहाँ करना चाहिए। Root cause बताता है क्या गलत है। Leverage point बताता है कहाँ act करना है।',
          '5f': 'आपने leverage point ढूँढा और दो groups के बीच जो communicate नहीं कर रहे उस gap पर position किया। अगला कदम: अपने clients के across देखिए। क्या यह same structural problem अलग-अलग companies में दिख रही है? अगर दो बार देख चुके हैं, तो यह client problem नहीं है। इस growth stage का pattern है। यह recognition बदल देती है कि आपकी skill market में कितनी valuable है।',
          '5g': 'आप multiple clients में pattern देखते हैं और इस class की problem diagnose और fix करने का approach बना रहे हैं। Market demand भी देखते हैं कि यह skill कहाँ जा रही है। अगला कदम: सिर्फ problem fix मत कीजिए। Client कैसे इस type की problem के बारे में सोचता है, वो बदलिए। अगर उनका mental model shift कर सकें, तो problem produce करना ही बंद करते हैं। यह सबसे high-leverage intervention है: सोच बदलना, system नहीं।',
          '5h': 'आप clients को problem के type के बारे में कैसे सोचते हैं वो बदलते हैं, सिर्फ specific instance नहीं। आपके interventions simple दिखते हैं लेकिन multiple surfaces पर behavior shift करते हैं क्योंकि system में सही point target करते हैं। आप इन dimensions पर highest level पर हैं। आपकी growth अब इसे एक ऐसी practice में बनाने से आएगी जो दूसरे आपसे सीख सकें।',
        },
      },
    ],
  },
};

export default hi;
